config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'books#top'

  get 'books' => 'books#main'

  post 'books' => 'books#create'

  get 'books/:id' => 'books#show', as: 'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def main
  	@books = Book.all
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
  		redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render 'main'
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)

      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
  	@book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path, notice: 'Book was successfully destroyed.'
      # else
      # render books_path, notice: "error!  I couldn't do it ..."
    end
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f| %>
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
		</div>
	<% end %>

	<div class="field_new">
		<h4 class="nb">Title</h4>
		<div><%= f.text_field :title %></div>

		<% if @book.errors.include?(:title) %>
			<p style="color: red;"><%= @book.errors.full_messages_for(:title).first %></p>
		<% end %>
	</div>
	<div class="field_new">
		<h4 class="nb">Body</h4>
		<div><%= f.text_area :body %></div><br>

		<% if @book.errors.include?(:body) %>
			<p style="color: red;"><%= @book.errors.full_messages_for(:body).first %></p>
		<% end %>
	</div>

	<div>
		<%= f.submit 'Create Book', class:"btn" %>
	</div>
<% end %>

app/views/books/_test.html.erb
<p>test</p>

app/views/books/edit.html.erb
<body class="edit_body">
	<h1 class="books_head">Editing Book</h1>

	<% if @book.errors.any? %>
		<div id="error_explanation">
			<p class="er_ti"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</p>

			<ul class="er_bd">
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
	<main>
		<div class="form_bt">
			<p class="nb"><span class="<%= "txred" if @book.errors.include?(:title) %>">Title</span></p>
			<div class="<%= "field_red" if @book.errors.include?(:title) %>"><%= f.text_field :title %></div>
		</div>
		<div class="form_bt">
			<p class="nb"><span class="<%= "txred" if @book.errors.include?(:body) %>">Body</span></p>
			<div class="<%= "field_red" if @book.errors.include?(:body) %>"><%= f.text_area :body %></div><br>
		</div>
		<div>
			<%= f.submit 'Update Book' %>
		</div>
	<% end %>
	</main>
	<div class="sb sb_t"><%= link_to 'Show', book_path(params[:id]) %></div>
	<p class="sb"> | </p>
	<div class="sb"><%= link_to 'Back', books_path %></div>
</body>

app/views/books/main.html.erb
<body class="books_body">
	<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
	<% end %>
	<header>
		<h1 class="books_head">Books</h1>
	</header>
	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Body</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td class="bl book_title"><%= book.title %></th>
				<td class="bl book_body"><%= book.body %></th>
				<td class="bl book_link"><%= link_to 'Show', book_path(book.id) %></th>
				<td class="bl book_link">
					<%= link_to 'Edit', edit_book_path(book.id) %>
				</td>
				<td class ="book_link">
					<%= link_to 'Destroy', destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure ?" %>
				</td>
			</tr>
			<% end %>
	</table>
	<h2 class="main_h2">New book</h2>
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<p class="er_ti"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</p>

			<ul class="er_bd">
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<%= form_for(@book) do |f| %>
	<div class="form_bt">
		<p class="nb"><span class="<%= "txred" if @book.errors.include?(:title) %>">Title</span></p>
		<div class="<%= "field_red" if @book.errors.include?(:title) %>"><%= f.text_field :title %></div>
	</div>
	<div class="form_bt">
		<p class="nb"><span class="<%= "txred" if @book.errors.include?(:body) %>">Body</span></p>
		<div class="<%= "field_red" if @book.errors.include?(:body) %>"><%= f.text_area :body %></div><br>
	</div>
	<div class="form_bt">
		<%= f.submit 'Create Book', class:"btn" %>
	</div>
<% end %>
</body>

app/views/books/show.html.erb
<body class="show_body">
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>
<p class="shp">
	<span class="bold">Title: </span><%= @book.title %>
</p>
<p class="shp">
	<span class="bold">Body: </span><%= @book.body %>
</p>
<div class="sb sb_t"><%= link_to 'Edit', edit_book_path(params[:id]) %></div>
	<p class="sb"> | </p>
	<div class="sb"><%= link_to 'Back', books_path %></div>
</body>


app/views/books/top.html.erb
<body class="roots_body">
	<header>
		<h1>ようこそ Bookers へ！</h1>
	</header>

	<main>
		<p class="top_main">
			<b>Bookers</b> では、さまざまな書籍に関するあなたの意見や
		</p>
		<p class ="top_main">
			印象を共有し交換することができます
		</p>
		<p class="top_main">
		<%= link_to 'start', books_path %>
		</p>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>